export const movie_list = 
[{  id :0,
	image: 'Dear zindagi.png',
	movie: 'Dear Zindagi',
	year: '2016',
	time: '2h 31m',
	junor: 'Drama Romance',
	description:'kaira is a building cinemagrapher in search of a perfect life. her encounter with jug, an unconventional thinker.helps her gain a new perspective on life .she discovers that happiness ia all about finding comfort in life"s imperfections.',
	likes:0,
	dislikes:0,
	},
{   id:1,
	image:'Brave.png',
	movie: 'Brave',
	year: '2012',
	time: '1h 33m',
	junor: 'Adventures, comedy',
	description:'Determind to make her own path in life, princess merida defins a custom that brings chaos to her kingdom granted one wish , marida must rely on her bravery and her archery skills to undo a beastly curse.',
	likes:0,
	dislikes:0,
	}, 
	
{   id:2,
	image:'Moana.png' ,
	movie: 'Moana',
	year: '2016',
	time: '1h 47m',
	junor: 'Adventures, comedy',
	description:'In ancient polynesia when a teritible curse incurred by the demingold maui reaches maona"s island .she answers the ocean call to seek out the demingold to set the things right',
	likes:0,
	dislikes:0,
	}, 
	
{    id:3,
	image: 'Mulan.png',
	movie: 'Mulan',
	year: '1998',
	time: '1h 27m',
	junor: 'Adventures, comedy',
	description:'to save her from death in the army .a youg maiden secretly goes in his place and bacomes one of chinas greatest heroines in the process.' ,
	likes:0,
	dislikes:0,
	}, 	
	
{   id:4,
	image: 'Malala.png',
	movie: 'He Named Me Malala',
	year: '2015',
	time: '1h 28m',
	junor: 'Biography, Documentary',
	description: 'a look At The leading up to the taibans attack on pakistani schoolgirl malala yousufzai for speaking out on girls Education followed by the Aftermath including her speech to the united nations. ',
	likes:0,
	dislikes:0,
	}, 
	
{   id:5,
	image: 'Soul.png',
	movie: 'Soul surfer',
	year: '2011',
	time: '1h 52m',
	junor: 'Drama, Biography, Family',
	description:'Teenage surfer Bethany Hamilton Overcomes The Odds And her Own And Her Own Fears Of Returning To The Water After Losing Her Left Arm In A shark Attack	',
	likes:0,
	dislikes:0,
	}, 
	
{   id:6,
	image: 'Beckham.png',
	movie: 'Bend It Like Beckham',
	year: '2002',
	time: '1h 52m',
	junor: 'comedy, drama & Romance',
	description:'Two Ambitious Girls Despite Their Parents Wishes Have Their Hearts Set On Careers In Professional FootBall.  ',
	likes:0,
	dislikes:0,
	}, 
	
{   id:7,
	image:'Wild.png',
	movie: 'Into The Wild',
	year: '2007',
	time: '2h 28m',
	junor: 'Adventures, Biograpgy, Drama',
	description:'After Graduating From University.Top Student and Athiete Christopher McCandless Abandons His Possessions, Gives His Entire $24,000 Saving Account To Charity And Hitchhikes To Alaska To Live In thr Wilderness Along The Way,Christopher Encounters A Series Of Characters That Shape His Life.',
	likes:0,
	dislikes:0,
	}, 
	
	
{   id:8,
	image:'Pursuit.jpg',
	movie: 'The Pursuit Of Happyness',
	year: '2006',
	time: '1h 57m',
	junor: 'Drama, Biograpgy',
	description:'A struggling Salesman takes custody of his son as hes poised to begin a life changing  professional career.',
	likes:0,
	dislikes:0,
	}, 
	
{   id:9,
	image:'Intouchables.png',
	movie: 'The Intouchables',
	year: '2011',
	time: '1h 52m',
	junor: 'Drama, Biograpgy',
	description:'After He Becomes A Quadriplegic From A paragliding Accident,an Aristocrat hires A Young man From The Project To Be His Caregiver.',
	likes:0,
	dislikes:0,
	}, 
	
]
